In [1]:
import numpy as np

In [421]:
a = [0,123,999]

tmp = np.random.choice(a, size=3, replace=False, p=None)
print(tmp)
tmp = np.random.choice(a, size=3, replace=False, p=None)
print(tmp)
tmp = np.random.choice(a, size=3, replace=False, p=None)
print(tmp)

[123 999   0]
[123   0 999]
[999   0 123]


In [422]:
cnt = 0
r = 10000
for i in range(r):
    tmp = np.random.choice(a, size=3, replace=False, p=None)
    if(tmp[0]==0): # first choice, always choose idx 0
        cnt+=1
print(cnt/r)

0.3366


In [425]:
# cheat
def cheat(arr):
    return np.argmin(arr, axis=0)

cnt = 0
r = 1
for i in range(r):
    tmp = np.random.choice(a, size=3, replace=False, p=None)
    print(tmp)
    print(cheat(tmp))

[999 123   0]
2


In [571]:
def cheat(arr):
    win = np.argmin(arr, axis=0)
    if(win==0):
        cheat=1
        suggest=2
    elif(win==1):
        cheat=2
        suggest=1
    elif(win==2):
        cheat=1
        suggest=2
    print("--现在作弊了，剩下的格子 %d 里没有奖品，不要选啊"%(cheat))
    return cheat,suggest

cnt = 0
r = 1
for i in range(r):
    tmp = np.random.choice(a, size=3, replace=False, p=None)
    first_time_choice = tmp[0]
    print("我现在选了 0 号格子，但是不公开获奖情况")
    cheat,suggest = cheat(tmp)
    print("--好的，我听你的，我放弃格子 0，改选格子 %d" % suggest)
    second_time_choice = tmp[suggest]
    print("现在看看我中奖没：%s" % str(second_time_choice==0))
    

我现在选了 0 号格子，但是不公开获奖情况
--现在作弊了，剩下的格子 1 里没有奖品，不要选啊
--好的，我听你的，我放弃格子 0，改选格子 2
现在看看我中奖没：False


In [562]:
def cheat(arr):
    win = np.argmin(arr, axis=0)
    if(win==0):
        cheat=1
        suggest=2
    elif(win==1):
        cheat=2
        suggest=1
    elif(win==2):
        cheat=1
        suggest=2
    return suggest

cnt = 0
r = 10000
for i in range(r):
    tmp = np.random.choice(a, size=3, replace=False, p=None)
    suggest = cheat(tmp)
    second_time_choice = tmp[suggest]
    if(second_time_choice==0):
        cnt+=1
print(cnt/r)

0.6696


In [8]:
pop(a)

NameError: name 'pop' is not defined