Finding the Value Function in MRP???

In [ ]:
import numpy as np
from scipy import linalg

In [ ]:
# define the Transition Probability Matrix
n_states = 3
P = np.zeros((n_states, n_states), np.float)
P[0, 1] = 0.7
P[0, 2] = 0.3
P[1, 0] = 0.5
P[1, 2] = 0.5
P[2, 1] = 0.1
P[2, 2] = 0.9
print(P)

[[0.  0.7 0.3]
 [0.5 0.  0.5]
 [0.  0.1 0.9]]


<ipython-input-3-88f36c8076a7>:3: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  P = np.zeros((n_states, n_states), np.float)


In [ ]:
# the sum over columns is 1 for each row being a probability matrix
assert((np.sum(P, axis=1) == 1).all())

In [ ]:
# define the reward matrix
R = np.zeros((n_states, n_states), np.float)
R[0, 1] = 1
R[0, 2] = 10
R[1, 0] = 0
R[1, 2] = 1
R[2, 1] = -1
R[2, 2] = 10

<ipython-input-5-261186755d66>:2: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  R = np.zeros((n_states, n_states), np.float)


In [ ]:
# calculate expected reward for each state by multiplying the probability matrix for each reward
R_expected = np.sum(P * R, axis=1, keepdims=True)

In [ ]:
# The matrix R_expected
R_expected

array([[3.7],
       [0.5],
       [8.9]])

In [ ]:
# define the discount factor
gamma = 0.9

In [ ]:
# Now it is possible to solve the Bellman Equation
A = np.eye(n_states) - gamma * P

In [ ]:
B = R_expected

In [ ]:
# solve using scipy linalg
V = linalg.solve(A, B)
V

array([[65.540732  ],
       [64.90791027],
       [77.5879575 ]])