In [1]:
import numpy as np
from scipy import linalg

In [19]:
n_states=3
p=np.zeros((n_states,n_states),np.float)
R=np.zeros_like(p)


/var/folders/lm/kt3nd3_d5xbdlqg_f3xz91y40000gn/T/ipykernel_84269/1590824401.py:2: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  p=np.zeros((n_states,n_states),np.float)


In [25]:
p[0,1],R[0,1]=0.7,1
p[0,2],R[0,2]=0.3,10
p[1,0],R[1,0]=0.5,0
p[1,2],R[1,2]=0.5,1
p[2,1],R[2,1]=0.1,-1
p[2,2],R[2,2]=0.9,10
print(p,'\n\n',R)

[[0.  0.7 0.3]
 [0.5 0.  0.5]
 [0.  0.1 0.9]] 

 [[ 0.  1. 10.]
 [ 0.  0.  1.]
 [ 0. -1. 10.]]


In [26]:
R_expected=np.sum(p*R, axis=1, keepdims=True)
print(R_expected)

[[3.7]
 [0.5]
 [8.9]]


In [27]:
np.dot(p,R)

array([[ 0. , -0.3,  3.7],
       [ 0. ,  0. , 10. ],
       [ 0. , -0.9,  9.1]])

In [28]:
p*R

array([[ 0. ,  0.7,  3. ],
       [ 0. ,  0. ,  0.5],
       [ 0. , -0.1,  9. ]])

In [30]:
gamma=0.9
A = np.eye(n_states) - gamma*p
B = R_expected
v = linalg.solve(A,B)
v

array([[65.540732  ],
       [64.90791027],
       [77.5879575 ]])